name: test
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  test:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Test with the Go CLI
        run: "go test -v ./..."
